# Workflow to
# 1. Build Image
# 2. Push to ECR
# 4. SSH to server
# 4. Pull && Run Image

name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-west-1
  AWS_ACCOUNT_ID: 540222592911
  CLICOLOR: 1

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: write    # This is required for actions/checkout


jobs:
  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4
    - name: Spell Check Repo
      uses: crate-ci/typos@v1.31.1
  deploy:
    runs-on: ubuntu-latest
    needs: spelling
    steps:
      - name: SSH into EC2 Machine and Restart website
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOSTNAME: nicolabeirer.com
          USER_NAME: ${{secrets.USER_NAME}}
        run: |
          echo "$PRIVATE_KEY" >> private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu/Personal-Website
            git pull origin main
            npm install --production
            /home/ubuntu/.nvm/versions/node/v20.11.0/bin/pm2 restart 0
            '
